### ISSUE TITLE
Extract png from pkg

### ISSUE THREAD

**Issue by mrdude2478** [hippie68/sfo#3]
Is it possible to add a feature to extract the game PNG from a PKG file?

Game PNG offset address shown in all pgk files I have tested:

0x2d30 - 4 bytes starting at this offset shows png offset address location
0x2d34 - 4 bytes shows png offset size (add address given by starting offset to this give png end offset).

Also I don't know if you know but, offsets in all pkg files I tested:
0x2bf0 - 4 bytes shows SFO offset address
0x2bf4 - 4 bytes shows size of SFO file

**Comment by hippie68** [comment]
It is possible, but has nothing to do with param.sfo, so I won't add it to this particular program.

If you want to do it, this article describes how PKGs are structured:
https://www.psdevwiki.com/ps4/Package_Files

The address may be the same in the PKGs you have tested, but IMO it is better not to rely on that but instead use the values found in the PKG structure.

**Comment by mrdude2478** [comment]
Thanks, it only works on game pkg - I managed to do it with c# already. Thanks for the link - I'll have a read.
